### ISSUE TITLE
Content of Codemirror Field is Deleted on Save in Craft 3.2.1

### ISSUE THREAD

**Issue by kerrig** [luwes/craft3-codemirror#13]
I have a Codemirror field that is required on an entry in my Craft instance. When I try to save the entry, the content that is entered in the Codemirror field gets deleted and the field throws an error saying "[Field name] cannot be blank." and the entry cannot be saved (since the field is required).

Craft CMS Version 3.2.1

I originally noticed this broke when my site updated to 3.2 beta versions and thought maybe the official release would fix, but looks like that's not the case.

If you need any additional information, please let me know! Thanks!

**Comment by vaughn-taylor** [comment]
I have this issue as well. It's related to a missing resource in the control panel. CodeMirror is bombing out because of the missing resource:

https://.../cpresources/4893766c/mode/scss/scss.js net::ERR_ABORTED 404

**Comment by vaughn-taylor** [comment]
I tried uninstalling / reinstalling the plugin but that didn't resolve the issue.

**Comment by timbertens** [comment]
Same thing here, in meanwhile running craft 3.2.8

**Comment by jeffturcotte** [comment]
Here's a pull request that resolves this issue. https://github.com/luwes/craft3-codemirror/pull/14

**Comment by luwes** [comment]
sorry for not being active here. I merged @jeffturcotte's fix. hope this resolves the issue in version 1.0.2.
