### ISSUE TITLE
CRAFT 4 info

### ISSUE THREAD

**Issue by Djive** [luwes/craft3-codemirror#21]
Hey :)

You said you merged PR for craft 4 .. 

but still not avaible to download in Craft store..

any info on that

**Comment by luwes** [comment]
I contacted Craft CMS, hope they can update it soon. Cheers! 
cc @brandonkelly

**Comment by wmdhosting** [comment]
thats all automatic,, 
https://craftcms.com/docs/4.x/extend/updating-plugins.html#high-level-notes
