### ISSUE TITLE
[Bug] Content not shown when field is on a secondary tab

### ISSUE THREAD

**Issue by mattcdavis1** [luwes/craft3-codemirror#6]
When a CodeMirror field is assigned to a non-default tab, the content of the field will not show until you click in the field.

**Comment by richhayler** [comment]
Give this a go, it worked for me....

edit your CodeMirror config file to include the following add-on and autoRefresh setting.

`return [
	"jsOptions" => [
        "autoRefresh" => true,
	],
	"addons" => [
		"display/autorefresh",
	]
];`

**Comment by luwes** [comment]
Duplicate of #10
