### ISSUE TITLE
JavaScript needs to re-init when switching tabs (like under a global set).

### ISSUE THREAD

**Issue by 23d1** [luwes/craft3-codemirror#7]
As title. Doesn't layout properly, so it needs to init again to capture the input field and apply JS.

**Comment by richhayler** [comment]
Give this a go, it worked for me....

edit your CodeMirror config file to include the following add-on and autoRefresh setting.

`return [
	"jsOptions" => [
        "autoRefresh" => true,
	],
	"addons" => [
		"display/autorefresh",
	]
];`

**Comment by luwes** [comment]
Duplicate of #10
